# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present
      env:
        CUBIPOOL_POSTGRESQL_URL:  ${{ secrets.CUBIPOOL_POSTGRESQL_URL }} 

    - name: Format code with Prettier
      run: npm run format

    - name: Commit format changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply formatting changes
        branch: ${{ github.head_ref }}

    - name: Login to Heroku Container registry
      env: 
        HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
      run: heroku container:login

    - name: Build and push
      env:
        HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
      run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web 
      
    - name: Release
      env:
        HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
      run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web 
